version: "3"
services:
  web_alexrogna:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3000:3000"
    volumes: 
      - ./alexrogna:/opt/app
      - gem_cache_alexrogna:/gems
    env_file: 
      - .env/development/database_alexrogna
      - .env/development/web_alexrogna
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_alexrogna
    networks:
      - network
  webpack_dev_server_alexrogna:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "4000:3035"
    volumes: 
      - ./alexrogna:/opt/app
      - gem_cache_alexrogna:/gems
    env_file: 
      - .env/development/database_alexrogna
      - .env/development/web_alexrogna
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_alexrogna:
    image: postgres:13
    env_file: 
      - .env/development/database_alexrogna
    volumes: 
      - db_data_alexrogna:/var/lib/postgresql/data
    networks:
      - network
volumes: 
  db_data_alexrogna:
  gem_cache_alexrogna:
networks:
  network: