# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user = CreateAdminService.new.call

ActionText::RichText.create!(record_type: 'User',record_id: user.id, name: 'long_description_wysiwyg', body: "I'm a <strong>web designer</strong> and <strong>programmer</strong> specialized in creating useful applications and beautiful websites. I've been in the field for more than <strong>5 years</strong> and have been loving every minute of it! I'm an entrepreneur, designer, developer and overall a thinker. I have experience in all phases of the project life cycle - <strong>analysis</strong>,<strong> design</strong>,<strong> coding</strong>, <strong>debugging</strong>, <strong>testing</strong> and <strong>implementation</strong>. My working experience is the proof that I can be an excellent asset to your company.")
ActionText::RichText.create!(record_type: 'User',record_id: user.id, name: 'extra_description_for_pdf', body: "Find more details about me and my portfolio of projects on my website <a href=\"https://alexrogna.com\">alexrogna.com</a>")
user.cover_image.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/cover_image.jpg')), filename: 'cover_image.jpg')
user.profile_image.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/profile_image.jpg')), filename: 'profile_image.jpg')

#Social icons
SocialIcon.create!(name: 'LinkedIn', link: 'https://www.linkedin.com/in/alexrogna/', icon: 'fab fa-linkedin-in')
SocialIcon.create!(name: 'GitHub', link: 'https://github.com/AlexUkPC', icon: 'fab fa-github')
SocialIcon.create!(name: 'DockerHub', link: 'https://hub.docker.com/u/alexrogna', icon: 'fab fa-docker', show_on_cv: false)

#Skills
skill1 = Skill.create!(name: 'Ruby', order_id: '1')
skill1.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/Ruby.png')), filename: 'ruby.png')
skill2 = Skill.create!(name: 'Rails', order_id: '2')
skill2.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/Rails.png')), filename: 'rails.png')
skill3 = Skill.create!(name: 'HTML', order_id: '3')
skill3.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/HTML.png')), filename: 'html.png')
skill4 = Skill.create!(name: 'CSS', order_id: '4')
skill4.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/CSS.png')), filename: 'css.png')
skill5 = Skill.create!(name: 'JavaScript', order_id: '5')
skill5.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/Javascript.png')), filename: 'javascript.png')
skill6 = Skill.create!(name: 'Wordpress', order_id: '6')
skill6.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/WordPress.png')), filename: 'wordpress.png')
skill7 = Skill.create!(name: 'Databases', order_id: '7')
skill7.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/Databases.png')), filename: 'databases.png')
skill8 = Skill.create!(name: 'Linux', order_id: '8')
skill8.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/Linux.png')), filename: 'linux.png')
skill9 = Skill.create!(name: 'Git', order_id: '9')
skill9.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/Git.png')), filename: 'git.png')
skill10 = Skill.create!(name: 'Docker', order_id: '10')
skill10.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Skills/Docker.png')), filename: 'docker.png')

#Language skills
LanguageSkill.create!(language: "English", certificate_name: "EF SET Certificate", certificate_url: "https://efset.org/cert/ExPscw", procent: 66)
LanguageSkill.create!(language: "German",certificate_name: "", certificate_url: "", procent: 33)
LanguageSkill.create!(language: "Romanian",is_native: true, procent: 99)

#Personal skills
PersonalSkill.create!(skill: "Problem solving", icon: "fas fa-puzzle-piece", description: "In my mind, there's no problem without a solution. When I have a problem, I divide it into small parts and solve each one separately. After defining all possible solutions, I try to choose the best ones.", order_id: 1)
PersonalSkill.create!(skill: "Adaptability", icon: "fas fa-users-cog", description: "As a freelancer, I had to adapt myself to changes very often - different clients, areas, tools and technologies.", order_id: 2)
PersonalSkill.create!(skill: "Communication", icon: "fas fa-users", description: "Having a continuous exchange of information with my clients helped me to be able to express my ideas and implement the proposals from them.", order_id: 3)
PersonalSkill.create!(skill: "Keen eye for detail", icon: "fas fa-search", description: "I zoom in and verify every small detail in order to obtain better results, always keeping in mind how they could affect the success of the project.", order_id: 4)
PersonalSkill.create!(skill: "Self-motivation", icon: "fas fa-chart-line", description: "Successfully completing one project and moving on to the next one is very exciting for me. I'm passionate about my work and truly enjoy working towards the next big goal.", order_id: 5)
PersonalSkill.create!(skill: "Willingness to learn", icon: "fas fa-book-reader", description: "I'm very excited to discover new tools and technologies by reading books, taking online courses and experimenting.", order_id: 6)
PersonalSkill.create!(skill: "Planning", icon: "fas fa-tasks", description: "I'm a strategic planner, skilled in multitasking and prioritizing work tasks to meet any deadline.", order_id: 7)
PersonalSkill.create!(skill: "Time management", icon: "fas fa-user-clock", description: "I like to make every day a to-do list for myself that includes the tasks I need to complete within that day.", order_id: 8)
PersonalSkill.create!(skill: "Punctuality", icon: "far fa-clock", description: "It's really important to me to be punctual and I understand how important it is also for the team and for the organizational success. ", order_id: 9)

#Tech
tech1 = Tech.create!(name: "Ruby", order_id: 1)
tech1.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Ruby.png')), filename: 'ruby.png')
tech2 = Tech.create!(name: "Rails", order_id: 2)
tech2.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Rails.png')), filename: 'rails.png')
tech3 = Tech.create!(name: "Sqlite", order_id: 3, skill_ids: [skill7.id])
tech3.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/SQLite.png')), filename: 'sqlite.png')
tech4 = Tech.create!(name: "Postgresql", order_id: 4, skill_ids: [skill7.id])
tech4.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/PostgreSQL.png')), filename: 'postgresql.png')
tech5 = Tech.create!(name: "Python", order_id: 5)
tech5.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Python.png')), filename: 'python.png')
tech6 = Tech.create!(name: "PHP", order_id: 6)
tech6.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/PHP.png')), filename: 'php.png')
tech7 = Tech.create!(name: "Sql Server", order_id: 7, skill_ids: [skill7.id])
tech7.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/SQLServer.png')), filename: 'sqlserver.png')
tech8 = Tech.create!(name: "Turbo Pascal", order_id: 8)
tech8.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/TurboPascal.png')), filename: 'turbopascal.png')
tech9 = Tech.create!(name: "FoxPro", order_id: 9, skill_ids: [skill7.id])
tech9.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/FoxPro.png')), filename: 'foxpro.png')
tech10 = Tech.create!(name: "C++", order_id: 10)
tech10.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/C++.png')), filename: 'c++.png')
tech11 = Tech.create!(name: "SQL", order_id: 11, skill_ids: [skill7.id])
tech11.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/SQL.png')), filename: 'sql.png')
tech12 = Tech.create!(name: "C#", order_id: 12)
tech12.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/C#.png')), filename: 'c#.png')
tech13 = Tech.create!(name: "Java", order_id: 13)
tech13.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Java.png')), filename: 'java.png')
tech14 = Tech.create!(name: "Visual Basic", order_id: 14)
tech14.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/VisualBasic.png')), filename: 'visualbasic.png')
tech15 = Tech.create!(name: "MySql", order_id: 15, skill_ids: [skill7.id])
tech15.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/MySql.png')), filename: 'mysql.png')
tech16 = Tech.create!(name: "HTML", order_id: 16)
tech16.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/HTML.png')), filename: 'html.png')
tech17 = Tech.create!(name: "CSS", order_id: 17)
tech17.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/CSS.png')), filename: 'css.png')
tech18 = Tech.create!(name: "Sass", order_id: 18)
tech18.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Sass.png')), filename: 'sass.png')
tech19 = Tech.create!(name: "Bulma", order_id: 19)
tech19.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Bulma.png')), filename: 'bulma.png')
tech20 = Tech.create!(name: "Bootstrap", order_id: 20)
tech20.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Bootstrap.png')), filename: 'bootstrap.png')
tech21 = Tech.create!(name: "Tailwind", order_id: 21)
tech21.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Tailwind.png')), filename: 'tailwind.png')
tech22 = Tech.create!(name: "Javascript", order_id: 22)
tech22.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Javascript.png')), filename: 'javascript.png')
tech23 = Tech.create!(name: "Jquery", order_id: 23, skill_ids: [skill5.id])
tech23.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/jQuery.png')), filename: 'jquery.png')
tech24 = Tech.create!(name: "React", order_id: 24)
tech24.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/React.png')), filename: 'react.png')
tech25 = Tech.create!(name: "Wordpress", order_id: 25)
tech25.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/WordPress.png')), filename: 'wordpress.png')
tech26 = Tech.create!(name: "WooCommerce", order_id: 26)
tech26.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/WooCommerce.png')), filename: 'woocommerce.png')
tech27 = Tech.create!(name: "IntelliJ Idea", order_id: 27)
tech27.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/IntelliJ.png')), filename: 'intellij.png')
tech28 = Tech.create!(name: "Android Studio", order_id: 28)
tech28.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/AndroidStudio.png')), filename: 'androidstudio.png')
tech29 = Tech.create!(name: "RubyMine", order_id: 29)
tech29.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/RubyMine.png')), filename: 'rubymine.png')
tech30 = Tech.create!(name: "Visual Studio Code", order_id: 30)
tech30.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/VisualStudioCode.png')), filename: 'visualstudiocode.png')
tech31 = Tech.create!(name: "Figma", order_id: 31)
tech31.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Figma.png')), filename: 'figma.png')
tech32 = Tech.create!(name: "Notion", order_id: 32)
tech32.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Notion.png')), filename: 'notion.png')
tech33 = Tech.create!(name: "Linux", order_id: 33)
tech33.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Linux.png')), filename: 'linux.png')
tech34 = Tech.create!(name: "Nginx", order_id: 34)
tech34.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Nginx.png')), filename: 'nginx.png')
tech35 = Tech.create!(name: "Magento", order_id: 35)
tech35.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Magento.png')), filename: 'magento.png')
tech36 = Tech.create!(name: "PrestaShop", order_id: 36)
tech36.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/PrestaShop.png')), filename: 'prestashop.png')
tech37 = Tech.create!(name: "Odoo", order_id: 37)
tech37.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Odoo.png')), filename: 'odoo.png')
tech38 = Tech.create!(name: "Umbraco", order_id: 38)
tech38.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Umbraco.png')), filename: 'umbraco.png')
tech39 = Tech.create!(name: "Aptana", order_id: 39)
tech39.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Aptana.png')), filename: 'aptana.png')
tech40 = Tech.create!(name: "Windows Server", order_id: 40)
tech40.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/WindowsServer.png')), filename: 'windowsserver.png')
tech41 = Tech.create!(name: "Xampp", order_id: 41)
tech41.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Xampp.png')), filename: 'xampp.png')
tech42 = Tech.create!(name: "OpenCart", order_id: 42)
tech42.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/OpenCart.png')), filename: 'opencart.png')
tech43 = Tech.create!(name: "Atom", order_id: 43)
tech43.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Atom.png')), filename: 'atom.png')
tech44 = Tech.create!(name: "Visual Studio", order_id: 44)
tech44.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/VisualStudio.png')), filename: 'visualstudio.png')
tech45 = Tech.create!(name: "Eclipse", order_id: 45)
tech45.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Eclipse.png')), filename: 'eclipse.png')
tech46 = Tech.create!(name: "Wamp", order_id: 46)
tech46.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Wamp.png')), filename: 'wamp.png')
tech47 = Tech.create!(name: "CPanel", order_id: 47)
tech47.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Cpanel.png')), filename: 'cpanel.png')
tech48 = Tech.create!(name: "Filezilla", order_id: 48)
tech48.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Filezilla.png')), filename: 'filezilla.png')
tech49 = Tech.create!(name: "Git", order_id: 49)
tech49.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Git.png')), filename: 'git.png')
tech50 = Tech.create!(name: "Docker", order_id: 50)
tech50.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Docker.png')), filename: 'docker.png')
tech51 = Tech.create!(name: "Asana", order_id: 51)
tech51.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Asana.png')), filename: 'asana.png')
tech52 = Tech.create!(name: "Harvest", order_id: 52)
tech52.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Harvest.png')), filename: 'harvest.png')
tech53 = Tech.create!(name: "Corel Draw", order_id: 53)
tech53.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Corel.png')), filename: 'corel.png')
tech54 = Tech.create!(name: "Photoshop", order_id: 54)
tech54.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Photoshop.png')), filename: 'photoshop.png')
tech55 = Tech.create!(name: "After Effects", order_id: 55)
tech55.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/AfterEffects.png')), filename: 'aftereffects.png')
tech56 = Tech.create!(name: "Premier Pro", order_id: 56)
tech56.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/PremierPro.png')), filename: 'premierpro.png')
tech57 = Tech.create!(name: "VirtualBox", order_id: 57)
tech57.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/VirtualBox.png')), filename: 'virtualbox.png')
tech58 = Tech.create!(name: "VmWare", order_id: 58)
tech58.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/VmWare.png')), filename: 'vmware.png')
tech59 = Tech.create!(name: "Office Suite", order_id: 59)
tech59.logo.attach(io: File.open(Rails.root.join('app/assets/images/for_seed/Tech/Office.png')), filename: 'office.png')

# Work Experience
work1 = Work.create!(company: "DESTINE BROKER DE ASIGURARE - Ploiesti, RO", position: "Network Administrator and IT Support", start_date: "2008-01-03", end_date: "2014-06-15", tech_ids: [tech12.id, tech53.id, tech47.id, tech17.id, tech45.id, tech48.id, tech16.id, tech13.id, tech15.id, tech59.id, tech54.id, tech14.id, tech44.id, tech58.id, tech46.id] )
ActionText::RichText.create!(record_type: 'Work',record_id: work1.id, name: 'key_responsibilities', body: "<ul><li>Maintained the servers by regularly troubleshooting them, keeping a backup of information and restoring it in time of need. </li><li>Planned the networking in the office, maintained the user accounts and passwords, safeguarding the network from viruses and spam. </li><li>Designed, programmed, tested and implemented business systems and support client server applications using C# and MYSQL. </li><li>Used Visual Basics to build user defined functions and automate processes. </li></ul>")

work2 = Work.create!(company: "SEMPRE SANO CATERING - Bucharest, RO", position: "C# Developer", start_date: "2014-07-01", end_date: "2014-12-01", tech_ids: [tech12.id, tech47.id, tech17.id, tech48.id, tech16.id, tech15.id, tech44.id, tech46.id, tech26.id, tech25.id])
ActionText::RichText.create!(record_type: 'Work',record_id: work2.id, name: 'key_responsibilities', body: "<ul><li>Developed the internal software and the external presentation website. </li><li>Generated, maintained and archived the content of the website . </li><li>Provided ongoing problem-solving support of applications and implementation of the web services.</li></ul>")

work3 = Work.create!(company: "ARTCANDLE - Ploiesti, RO", position: "Web developer", start_date: "2015-05-01", end_date: "2016-08-01", tech_ids: [tech43.id, tech47.id, tech17.id, tech48.id, tech16.id, tech15.id, tech54.id, tech6.id, tech36.id, tech46.id])
ActionText::RichText.create!(record_type: 'Work',record_id: work3.id, name: 'key_responsibilities', body: "<ul><li>Defined website architecture and overall site structure. </li><li>Prepared, coded, installed, tested and debugged web applications using appropriate editors.</li><li>Assured security and backups of all websites and related applications.</li></ul>")

work4 = Work.create!(company: "LOGIT SOLUTIONS - Ploiesti, RO", position: "Programmer and Web developer", start_date: "2016-09-01", end_date: "2016-12-01", tech_ids: [tech39.id, tech20.id, tech12.id, tech47.id, tech17.id, tech48.id, tech16.id, tech22.id, tech35.id, tech37.id, tech6.id, tech36.id, tech5.id, tech7.id, tech38.id, tech40.id, tech41.id])
ActionText::RichText.create!(record_type: 'Work',record_id: work4.id, name: 'key_responsibilities', body: "<ul><li>Coded, debugged and documented modules in Python and C# for different CMS, based on clients requests. </li><li>Designed and updated websites on PrestaShop and Magento.</li></ul>")

work5 = Work.create!(company: "FREELANCER", position: "Programmer and Web developer", start_date: "2016-12-01", end_date: "2022-12-01", present: true, tech_ids: [tech28.id, tech51.id, tech20.id, tech19.id, tech53.id, tech47.id, tech17.id, tech50.id, tech31.id, tech48.id, tech49.id, tech52.id, tech16.id, tech27.id, tech22.id, tech23.id, tech33.id, tech15.id, tech34.id, tech32.id, tech54.id, tech4.id, tech2.id, tech24.id, tech1.id, tech29.id, tech18.id, tech3.id, tech21.id, tech57.id, tech30.id, tech25.id])
ActionText::RichText.create!(record_type: 'Work',record_id: work5.id, name: 'key_responsibilities', body: "<ul><li>Coded, debugged, tested and documented web applications based on customer requests. </li><li>Designed, created, updated, assured security and backups for websites.</li><li>Learned new tools and technologies to help me achieve my goals.</li></ul>")

#Education
education1 = Education.create!(school: "TOMA N. SOCOLESCU HIGH SCHOOL", location: "Ploiesti, RO", start_date: "2003-09-15", end_date: "2007-06-15", specialization: "Mathematics - Computer Science", tech_ids: [tech9.id, tech59.id, tech8.id ], show_on_cv: false )
ActionText::RichText.create!(record_type: 'Education',record_id: education1.id, name: 'courses', body: "<div>ECDL &amp; CISCO Course</div>")

education2 = Education.create!(school: "SPIRU HARET UNIVERSITY", location: "Bucharest, RO", start_date: "2009-10-01", end_date: "2012-06-01", specialization: "Faculty of Mathematics and Computer Science", tech_ids: [tech10.id, tech11.id ], show_on_cv: true )
ActionText::RichText.create!(record_type: 'Education',record_id: education2.id, name: 'courses', body: "<div>Bachelor's degree in Computer Science - 2021</div>")

education3 = Education.create!(school: "Purple Beard Training", location: "UK", start_date: "2021-12-09", end_date: "2022-03-15", specialization: "DevOps Course ", tech_ids: [tech50.id, tech49.id ], show_on_cv: true )